### ISSUE TITLE
BookingLocation gem in TAP

### ISSUE THREAD

**Issue by philManWithBeard** [guidance-guarantee-programme/telephone_appointment_planner#862]
Hi Ben,
I was thinking of forking TAP and seeing if I could surface a few locations into it using your BookingLocations GEM. I was then going to migrate booking_location_id on to a few tables and update the schedules view to do something like this: 
![image](https://user-images.githubusercontent.com/48831325/196735519-8cb6e7ef-87c8-469f-afdc-e308dd035465.png)

I'm not a dev, so not doing it for work, more just as a personal development thing in my own time. Any encouragement would be great. 
Phil

**Comment by benlovell** [comment]
Hi @philManWithBeard I've only just noticed this. Is it something you're still interested in attempting?
